MeetingRoom.VDI.Web/Models/LayoutViewModel.cs
using Mvc.JQuery.Datatables;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MeetingRoom.VDI.Web.Models
{
    public class LayoutViewModel
    {
        public int Id { get; set; }
        [DisplayName("Description")]
        [DataTables(Width = "200px")]
        public string meetingRoomLayoutDescription { get; set; }
        [DisplayName("Image Layout")]
        [DataTables(Width = "50px")]
        public byte[] meetingRoomLayoutImages { get; set; }
        [DisplayName("Title")]
        [DataTables(Width = "50px")]
        public string meetingRoomLayoutTitle { get; set; }
        [DisplayName("Price")]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public int meetingRoomLayoutPrice { get; set; }
        [DisplayName("Capacity")]
        public int meetingRoomLayoutCapacity { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
    }

    public class CreateLayoutViewModel
    {
        public int Id { get; set; }
        [DisplayName("Description")]
        [DataTables(Width = "200px")]
        public string meetingRoomLayoutDescription { get; set; }
        [DisplayName("Image Layout")]
        [DataTables(Width = "50px")]
        public byte[] meetingRoomLayoutImages { get; set; }
        [DisplayName("Title")]
        [DataTables(Width = "50px")]
        public string meetingRoomLayoutTitle { get; set; }
        [DisplayName("Price")]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public int meetingRoomLayoutPrice { get; set; }
        [DisplayName("Capacity")]
        public int meetingRoomLayoutCapacity { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
    }

    public class EditLayoutViewModel
    {
        public int Id { get; set; }
        [DisplayName("Description")]
        [DataTables(Width = "200px")]
        public string meetingRoomLayoutDescription { get; set; }
        [DisplayName("Image Layout")]
        [DataTables(Width = "50px")]
        public byte[] meetingRoomLayoutImages { get; set; }
        [DisplayName("Title")]
        [DataTables(Width = "50px")]
        public string meetingRoomLayoutTitle { get; set; }
        [DisplayName("Price")]
        //[DisplayFormat(DataFormatString = "{0:C0}", ApplyFormatInEditMode = true)]
        public int meetingRoomLayoutPrice { get; set; }
        [DisplayName("Capacity")]
        public int meetingRoomLayoutCapacity { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
    }
}

MeetingRoom.VDI.Web/Controllers/LayoutController.cs
using AutoMapper;
using MeetingRoom.VDI.Core.Interfaces;
using MeetingRoom.VDI.Core.Models;
using MeetingRoom.VDI.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetingRoom.VDI.Web.Controllers
{
    public class LayoutController : Controller
    {
        private readonly ILayout _LayoutService;

        public LayoutController(ILayout LayoutService)
        {
            _LayoutService = LayoutService;
        }
        public ActionResult LayoutList()
        {
            var output = _LayoutService.GetAll();
            return PartialView(output);
        }

        public FileContentResult GetFile(int id)
        {
            Layout mediaImage = _LayoutService.GetById(id);
            return new FileContentResult(mediaImage.meetingRoomLayoutImages, "image/*");
        }

        // GET: Layout
        public ActionResult Index()
        {
            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var output = _LayoutService.GetAll();

            return View(output);
        }

        // GET: Layout/Details/5
        public ActionResult Details(int id)
        {
            //if (!SecurityHelper.IsUserInTeam("SupervisorInventory"))
            //    return RedirectToAction("AccessDenied", "Account");

            var Layout = _LayoutService.GetById(id);

            Mapper.CreateMap<Layout, LayoutViewModel>();
            var model = Mapper.Map<Layout, LayoutViewModel>(Layout);

            if (model.meetingRoomLayoutImages != null)
            {
                ViewBag.Base64String = "data:image/png;base64," + Convert.ToBase64String(model.meetingRoomLayoutImages, 0, model.meetingRoomLayoutImages.Length);
            }

            return View(model);
        }

        // GET: Layout/Create
        public ActionResult Create()
        {
            //if (!SecurityHelper.IsUserInTeam("SupervisorInventory"))
            //    return RedirectToAction("AccessDenied", "Account");

            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var model = new CreateLayoutViewModel();

            return View(model);
        }

        // POST: Layout/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateLayoutViewModel model)
        {
            if (ModelState.IsValid)
            {
                byte[] rawBytes = null;
                if (Request.Files.Count > 0)
                {
                    //var inputFile = Request.Files[0];
                    //Stream fileStream = inputFile.InputStream;
                    //rawBytes = new byte[fileStream.Length];
                    //fileStream.Read(rawBytes, 0, Convert.ToInt32(fileStream.Length));

                    var inputFile = Request.Files[0];
                    var fileNm = Request.Files[0].FileName;
                    HttpPostedFileBase hpf = Request.Files[0] as HttpPostedFileBase;
                    Stream fileStream = inputFile.InputStream;
                    rawBytes = new byte[fileStream.Length];
                    fileStream.Read(rawBytes, 0, Convert.ToInt32(fileStream.Length));
                    //string filePath = Path.Combine(HttpContext.Server.MapPath("~//App_Data//Layout//"));
                    //hpf.SaveAs(filePath + fileNm);
                }

                //foreach (string filesData in Request.Files)
                //{
                //    var fileNm = Request.Files[filesData].FileName;
                //    HttpPostedFileBase hpf = Request.Files[filesData] as HttpPostedFileBase;
                //    string filePath = Path.Combine(HttpContext.Server.MapPath("~//Your Folder Path//"));
                //    hpf.SaveAs(filePath + fileNm);
                //}

                Mapper.CreateMap<CreateLayoutViewModel, Layout>();

                var newLayout = Mapper.Map<CreateLayoutViewModel, Layout>(model);
                newLayout.meetingRoomLayoutImages = rawBytes;
                newLayout.meetingRoomLayoutFilePath = "";

                _LayoutService.Create(newLayout);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Layout/Edit/5
        public ActionResult Edit(int id)
        {
            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var Layout = _LayoutService.GetById(id);

            Mapper.CreateMap<Layout, EditLayoutViewModel>();
            var model = Mapper.Map<Layout, EditLayoutViewModel>(Layout);

            //ViewBag.Base64String = "data:image/png;base64," + Convert.ToBase64String(model.meetingRoomLayoutImages, 0, model.meetingRoomLayoutImages.Length);

            if (model.meetingRoomLayoutImages != null)
            {
                ViewBag.Base64String = "data:image/png;base64," + Convert.ToBase64String(model.meetingRoomLayoutImages, 0, model.meetingRoomLayoutImages.Length);
            }

            return View(model);
        }

        // POST: Layout/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EditLayoutViewModel model)
        {
            if (ModelState.IsValid)
            {
                byte[] rawBytes = null;
                if (Request.Files.Count > 0)
                {
                    var inputFile = Request.Files[0];
                    var fileNm = Request.Files[0].FileName;
                    HttpPostedFileBase hpf = Request.Files[0] as HttpPostedFileBase;
                    Stream fileStream = inputFile.InputStream;
                    rawBytes = new byte[fileStream.Length];
                    fileStream.Read(rawBytes, 0, Convert.ToInt32(fileStream.Length));
                    //string filePath = Path.Combine(HttpContext.Server.MapPath("~//App_Data//Layout//"));
                    //hpf.SaveAs(filePath + fileNm);
                }

                //foreach (string filesData in Request.Files)
                //{
                //    var fileNm = Request.Files[filesData].FileName;
                //    HttpPostedFileBase hpf = Request.Files[filesData] as HttpPostedFileBase;
                //    string filePath = Path.Combine(HttpContext.Server.MapPath("~//Your Folder Path//"));
                //    hpf.SaveAs(filePath + fileNm);
                //}

                Mapper.CreateMap<EditLayoutViewModel, Layout>();

                var editLayout = Mapper.Map<EditLayoutViewModel, Layout>(model);
                editLayout.meetingRoomLayoutImages = rawBytes;
                editLayout.meetingRoomLayoutFilePath = "FilePath";

                _LayoutService.Update(editLayout);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Layout/Delete/5
        public ActionResult Delete(int id)
        {
            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var Layout = _LayoutService.GetById(id);

            Mapper.CreateMap<Layout, EditLayoutViewModel>();
            var model = Mapper.Map<Layout, EditLayoutViewModel>(Layout);

            //ViewBag.Base64String = "data:image/png;base64," + Convert.ToBase64String(model.meetingRoomLayoutImages, 0, model.meetingRoomLayoutImages.Length);

            if (model.meetingRoomLayoutImages != null)
            {
                ViewBag.Base64String = "data:image/png;base64," + Convert.ToBase64String(model.meetingRoomLayoutImages, 0, model.meetingRoomLayoutImages.Length);
            }

            return View(model);
        }

        // POST: Layout/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, EditLayoutViewModel model)
        {
            try
            {
                // TODO: Add delete logic here
                Mapper.CreateMap<EditLayoutViewModel, Layout>();

                var deleteLayout = Mapper.Map<EditLayoutViewModel, Layout>(model);

                _LayoutService.Delete(deleteLayout.Id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public JsonResult GetLayoutCapacity(int id)
        {
            var layoutList = _LayoutService.GetCapacity(id);
            return Json(layoutList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetLayout()
        {
            var layoutList = _LayoutService.GetLayoutImage();
            return Json(layoutList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetLayoutById(int id)
        {
            var layoutList = _LayoutService.GetLayoutImageById(id);
            return Json(layoutList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetAllLayout()

MeetingRoom.VDI.Web/Views/Layout/Create.cshtml
@model MeetingRoom.VDI.Web.Models.CreateLayoutViewModel

@{
    ViewBag.Title = "Create Layout";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Create Layout</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Create Layout
            </div>
            <p></p>
            @using (Html.BeginForm("Create", "Layout", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomLayoutTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.EditorFor(model => model.meetingRoomLayoutTitle, new { htmlAttributes = new { @class = "form-control", @placeholder = "Layout Name", @style = "width:150px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomLayoutTitle, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomLayoutDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.TextAreaFor(model => model.meetingRoomLayoutDescription, new { htmlAttributes = new { style = "width:250px", rows = "3", @class = "form-control", @placeholder = "Layout Description" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomLayoutDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomLayoutPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            <span class="input-group-addon">Rp</span>
                            @Html.EditorFor(model => model.meetingRoomLayoutPrice, new { htmlAttributes = new { @class = "form-control", @placeholder = "Layout Price Per Hour", @style = "width:200px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomLayoutPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomLayoutCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.EditorFor(model => model.meetingRoomLayoutCapacity, new { htmlAttributes = new { @class = "form-control", @placeholder = "Layout Capacity", @style = "width:150px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomLayoutCapacity, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomLayoutImages, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            <input type="file" name="file" id="inputFile" multiple="multiple" />
                            <img id="displayImage" src="#" alt="Layout Here" style="height:100px;width:200px;" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                            <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "Layout")';return false;">Cancel</button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#displayImage').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#inputFile").change(function () {
        readURL(this);
    });
</script>

MeetingRoom.VDI.Web/Views/Layout/Delete.cshtml
@model MeetingRoom.VDI.Web.Models.EditLayoutViewModel

@{
    ViewBag.Title = "Edit Layout";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edit Layout</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Edit Layout
            </div>
            <p></p>

            @using (Html.BeginForm("Delete", "Layout", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomLayoutTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.EditorFor(model => model.meetingRoomLayoutTitle, new { htmlAttributes = new { @class = "form-control", @style = "width:150px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomLayoutTitle, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomLayoutDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.EditorFor(model => model.meetingRoomLayoutDescription, new { htmlAttributes = new { @class = "form-control", @style = "width:250px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomLayoutDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomLayoutPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            <span class="input-group-addon">Rp</span>
                            @Html.EditorFor(model => model.meetingRoomLayoutPrice, new { htmlAttributes = new { @class = "form-control", @style = "width:250px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomLayoutPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomLayoutCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.EditorFor(model => model.meetingRoomLayoutCapacity, new { htmlAttributes = new { @class = "form-control", @style = "width:150px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomLayoutCapacity, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomLayoutImages, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            <input type="file" name="file" id="inputFile" multiple="multiple" />
                            <p>
                                <img alt="" id="displayImage" src="@ViewBag.Base64String" style="height:100px;width:200px;" />
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Delete" class="btn btn-primary" />
                            <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "Layout")';return false;">Cancel</button>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#displayImage').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#inputFile").change(function () {
        readURL(this);
    });
</script>

MeetingRoom.VDI.Web/Views/Layout/Details.cshtml
@model MeetingRoom.VDI.Web.Models.LayoutViewModel

@{
    ViewBag.Title = "Details Layout";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Details Layout</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Details Layout
            </div>
            <input type="hidden" id="id" name="id" value=model.Id>
            <p></p>
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.meetingRoomLayoutTitle)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.meetingRoomLayoutTitle)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.meetingRoomLayoutDescription)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.meetingRoomLayoutDescription)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.meetingRoomLayoutPrice)
                    </dt>

                    <dd>
                        Rp. @Html.DisplayFor(model => model.meetingRoomLayoutPrice)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.meetingRoomLayoutCapacity)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.meetingRoomLayoutCapacity)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.meetingRoomLayoutImages)
                    </dt>

                    <dd>
                        <img alt="" src="@ViewBag.Base64String" style="height:100px;width:200px;" />
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>



<p>
    <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit", "Layout", new { id = Model.Id })';return false;">Edit</button>
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "Layout")';return false;">Cancel</button>
</p>

MeetingRoom.VDI.Web/Views/Layout/Edit.cshtml
@model MeetingRoom.VDI.Web.Models.EditLayoutViewModel

@{
    ViewBag.Title = "Edit Layout";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edit Layout</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Edit Layout
            </div>
            <p></p>

            @using (Html.BeginForm("Edit", "Layout", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.meetingRoomLayoutTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="form-group input-group">
                        @Html.EditorFor(model => model.meetingRoomLayoutTitle, new { htmlAttributes = new { @class = "form-control", @style = "width:150px" } })
                        @Html.ValidationMessageFor(model => model.meetingRoomLayoutTitle, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.meetingRoomLayoutDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="form-group input-group">
                        @Html.EditorFor(model => model.meetingRoomLayoutDescription, new { htmlAttributes = new { @class = "form-control", @style = "width:250px" } })
                        @Html.ValidationMessageFor(model => model.meetingRoomLayoutDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.meetingRoomLayoutPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="form-group input-group">
                        <span class="input-group-addon">Rp</span>
                        @Html.EditorFor(model => model.meetingRoomLayoutPrice, new { htmlAttributes = new { @class = "form-control", @style = "width:250px" } })
                        @Html.ValidationMessageFor(model => model.meetingRoomLayoutPrice, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.meetingRoomLayoutCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="form-group input-group">
                        @Html.EditorFor(model => model.meetingRoomLayoutCapacity, new { htmlAttributes = new { @class = "form-control", @style = "width:150px" } })
                        @Html.ValidationMessageFor(model => model.meetingRoomLayoutCapacity, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.meetingRoomLayoutImages, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="form-group input-group">
                        <input type="file" name="file" id="inputFile" multiple="multiple" />
                        <p>
                            <img alt="" id="displayImage" src="@ViewBag.Base64String" style="height:100px;width:200px;" />
                        </p>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "Layout")';return false;">Cancel</button>
                    </div>
                </div>
            </div>
            }

        </div>
    </div>
</div>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#displayImage').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#inputFile").change(function () {
        readURL(this);
    });
</script>