MeetingRoom.VDI.Web/Models/RoomViewModel.cs
using Mvc.JQuery.Datatables;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace MeetingRoom.VDI.Web.Models
{
    public class RoomViewModel
    {
        public int Id { get; set; }
        [DisplayName("Capacity")]
        [DataTables(Width = "100px")]
        public int MeetingRoomCapacity { get; set; }
        [DisplayName("Description")]
        [DataTables(Width = "200px")]
        public string MeetingRoomDescription { get; set; }
        [DisplayName("Prices")]
        [DataTables(Width = "100px")]
        public float MeetingRoomPrice { get; set; }
        [DisplayName("Status")]
        [DataTables(Width = "100px")]
        public bool MeetingRoomStatus { get; set; }
        [DisplayName("Title")]
        [DataTables(Width = "100px")]
        public string MeetingRoomTitle { get; set; }
        [DisplayName("Room Image")]
        [DataTables(Width = "100px")]
        public byte[] MeetingRoomImage { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        [DisplayName("Layout")]
        [DataTables(Width = "100px")]
        public int meetingRoomLayoutId { get; set; }
        [DisplayName("Book")]
        [DataTables(Width = "100px")]
        public byte meetingRoomBookFor { get; set; }
        [DisplayName("Layout")]
        [DataTables(Width = "100px")]
        public string LayoutName { get; set; }
    }

    public class CreateRoomViewModel
    {
        public int Id { get; set; }
        [DisplayName("Capacity")]
        [DataTables(Width = "100px")]
        public int MeetingRoomCapacity { get; set; }
        [DisplayName("Description")]
        [DataTables(Width = "200px")]
        public string MeetingRoomDescription { get; set; }
        [DisplayName("Prices")]
        [DataTables(Width = "100px")]
        public float MeetingRoomPrice { get; set; }
        [DisplayName("Status")]
        [DataTables(Width = "100px")]
        public bool MeetingRoomStatus { get; set; }
        [DisplayName("Title")]
        [DataTables(Width = "100px")]
        public string MeetingRoomTitle { get; set; }
        [DisplayName("Room Image")]
        [DataTables(Width = "100px")]
        public byte[] MeetingRoomImage { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        [DisplayName("Layout")]
        [DataTables(Width = "100px")]
        public int meetingRoomLayoutId { get; set; }
        [DisplayName("Book")]
        [DataTables(Width = "100px")]
        public byte meetingRoomBookFor { get; set; }
        [DisplayName("Layout")]
        [DataTables(Width = "100px")]
        public string LayoutName { get; set; }
    }

    public class EditRoomViewModel
    {
        public int Id { get; set; }
        [DisplayName("Capacity")]
        [DataTables(Width = "100px")]
        public int MeetingRoomCapacity { get; set; }
        [DisplayName("Description")]
        [DataTables(Width = "200px")]
        public string MeetingRoomDescription { get; set; }
        [DisplayName("Prices")]
        [DataTables(Width = "100px")]
        public float MeetingRoomPrice { get; set; }
        [DisplayName("Status")]
        [DataTables(Width = "100px")]
        public bool MeetingRoomStatus { get; set; }
        [DisplayName("Title")]
        [DataTables(Width = "100px")]
        public string MeetingRoomTitle { get; set; }
        [DisplayName("Room Image")]
        [DataTables(Width = "100px")]
        public byte[] MeetingRoomImage { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }       
        public int meetingRoomLayoutId { get; set; }
        [DisplayName("Book")]
        [DataTables(Width = "100px")]
        public byte meetingRoomBookFor { get; set; }
        [DisplayName("Layout")]
        [DataTables(Width = "100px")]
        public string LayoutName { get; set; }
    }
}

MeetingRoom.VDI.Web/Controllers/RoomController.cs
using AutoMapper;
using MeetingRoom.VDI.Core.Interfaces;
using MeetingRoom.VDI.Core.Models;
using MeetingRoom.VDI.Web.Helper;
using MeetingRoom.VDI.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetingRoom.VDI.Web.Controllers
{
    public class RoomController : Controller
    {

        private readonly IRoom _RoomService;
        private readonly ILayout _LayoutService;

        public RoomController(IRoom RoomService, ILayout LayoutService)
        {
            _RoomService = RoomService;
            _LayoutService = LayoutService;
        }

        public ActionResult RoomList()
        {
            return PartialView();
        }

        public FileContentResult GetFile(int id)
        {
            Room mediaImage = _RoomService.GetById(id);
            return new FileContentResult(mediaImage.MeetingRoomImage, "image/*");
        }

        // GET: Room
        public ActionResult Index()
        {
            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var output = _RoomService.GetAll();            

            return View(output);
        }

        // GET: Room/Details/5
        public ActionResult Details(int id)
        {
            //if (!SecurityHelper.IsUserInTeam("SupervisorInventory"))
            //    return RedirectToAction("AccessDenied", "Account");

            var Room = _RoomService.GetById(id);

            Mapper.CreateMap<Room, RoomViewModel>();
            var model = Mapper.Map<Room, RoomViewModel>(Room);

            ViewBag.Base64String = "data:image/png;base64," + Convert.ToBase64String(model.MeetingRoomImage, 0, model.MeetingRoomImage.Length);

            return View(model);
        }

        // GET: Room/Create
        public ActionResult Create()
        {
            //if (!SecurityHelper.IsUserInTeam("SupervisorInventory"))
            //    return RedirectToAction("AccessDenied", "Account");

            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var model = new CreateRoomViewModel();

            return View(model);
        }

        // POST: Room/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateRoomViewModel model)
        {
            if (ModelState.IsValid)
            {
                byte[] rawBytes = null;
                if (Request.Files.Count > 0)
                {
                    var inputFile = Request.Files[0];
                    var fileNm = Request.Files[0].FileName;
                    HttpPostedFileBase hpf = Request.Files[0] as HttpPostedFileBase;
                    Stream fileStream = inputFile.InputStream;
                    rawBytes = new byte[fileStream.Length];
                    fileStream.Read(rawBytes, 0, Convert.ToInt32(fileStream.Length));
                    //string filePath = Path.Combine(HttpContext.Server.MapPath("~//App_Data//Layout//"));
                    //hpf.SaveAs(filePath + fileNm);

                    //var file = Request.Files[0];
                    //Stream fileStream = file.InputStream;
                    //rawBytes = new byte[fileStream.Length];
                    //fileStream.Read(rawBytes, 0, Convert.ToInt32(fileStream.Length));
                }

                //foreach (string filesData in Request.Files)
                //{
                //    var fileNm = Request.Files[filesData].FileName;
                //    HttpPostedFileBase hpf = Request.Files[filesData] as HttpPostedFileBase;
                //    string filePath = Path.Combine(HttpContext.Server.MapPath("~//Your Folder Path//"));
                //    hpf.SaveAs(filePath + fileNm);
                //}

                Mapper.CreateMap<CreateRoomViewModel, Room>();
                
                var newRoom = Mapper.Map<CreateRoomViewModel, Room>(model);
                newRoom.CreationTime = System.DateTime.Now;
                newRoom.MeetingRoomImage = rawBytes;
                newRoom.MeetingRoomFilePath = "";

                //newSubBrand.IBy = User.Identity.Name;
                _RoomService.Create(newRoom);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Room/Edit/5
        public ActionResult Edit(int id)
        {
            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var Room = _RoomService.GetById(id);

            Mapper.CreateMap<Room, EditRoomViewModel>();
            var model = Mapper.Map<Room, EditRoomViewModel>(Room);

            ViewBag.Base64String = "data:image/png;base64," + Convert.ToBase64String(model.MeetingRoomImage, 0, model.MeetingRoomImage.Length);

            return View(model);
        }

        // POST: Room/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EditRoomViewModel model)
        {
            if (ModelState.IsValid)
            {
                byte[] rawBytes = null;
                if (Request.Files.Count > 0)
                {
                    var inputFile = Request.Files[0];
                    var fileNm = Request.Files[0].FileName;
                    HttpPostedFileBase hpf = Request.Files[0] as HttpPostedFileBase;
                    Stream fileStream = inputFile.InputStream;
                    rawBytes = new byte[fileStream.Length];
                    fileStream.Read(rawBytes, 0, Convert.ToInt32(fileStream.Length));
                    //string filePath = Path.Combine(HttpContext.Server.MapPath("~//App_Data//Layout//"));
                    //hpf.SaveAs(filePath + fileNm);

                    //var file = Request.Files[0];
                    //Stream fileStream = file.InputStream;
                    //rawBytes = new byte[fileStream.Length];
                    //fileStream.Read(rawBytes, 0, Convert.ToInt32(fileStream.Length));
                }

                //foreach (string filesData in Request.Files)
                //{
                //    var fileNm = Request.Files[filesData].FileName;
                //    HttpPostedFileBase hpf = Request.Files[filesData] as HttpPostedFileBase;
                //    string filePath = Path.Combine(HttpContext.Server.MapPath("~//Your Folder Path//"));
                //    hpf.SaveAs(filePath + fileNm);
                //}

                Mapper.CreateMap<EditRoomViewModel, Room>();
                //.ForMember(s => s.Brand, o => o.Ignore());

                var editRoom = Mapper.Map<EditRoomViewModel, Room>(model);
                editRoom.MeetingRoomImage = rawBytes;
                editRoom.MeetingRoomFilePath = "filePath";

                _RoomService.Update(editRoom);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Room/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Room/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public JsonResult GetRoom(int id)
        {
            var roomList = _RoomService.GetRoom(id);
            return Json(roomList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllRoom()
        {
            var roomList = _RoomService.GetAllRoom();
            return Json(roomList, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetRoomById(int id)
        {
            var roomList = _RoomService.GetLayoutImageByRoomId(id);
            return Json(roomList, JsonRequestBehavior.AllowGet);
        }
    }
}

MeetingRoom.VDI.Web/Views/Room/Create.cshtml
@model MeetingRoom.VDI.Web.Models.CreateRoomViewModel

@{
    ViewBag.Title = "Create Room";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Create Room</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Create Room
            </div>
            <p></p>
            @using (Html.BeginForm("Create", "Room", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.MeetingRoomTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MeetingRoomTitle, new { htmlAttributes = new { @class = "form-control", @placeholder = "Room Name", @style = "width:150px" } })
                            @Html.ValidationMessageFor(model => model.MeetingRoomTitle, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MeetingRoomImage, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" id="file" name="file" multiple="multiple" />
                            <img id="displayImage" src="#" alt="Layout" style="height:100px;width:200px;" />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MeetingRoomCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MeetingRoomCapacity, new { htmlAttributes = new { style = "width:250px", rows = "3", @class = "form-control", @placeholder = "Room Description" } })
                            @Html.ValidationMessageFor(model => model.MeetingRoomCapacity, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MeetingRoomDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.MeetingRoomDescription, new { htmlAttributes = new { style = "width:250px", rows = "3", @class = "form-control", @placeholder = "Room Description" } })
                            @Html.ValidationMessageFor(model => model.MeetingRoomDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MeetingRoomPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MeetingRoomPrice, new { htmlAttributes = new { style = "width:250px", rows = "3", @class = "form-control", @placeholder = "Room Description" } })
                            @Html.ValidationMessageFor(model => model.MeetingRoomPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LayoutName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="input-group">
                                @Html.DropDownList("LayoutName", new SelectList(Enumerable.Empty<SelectListItem>()))
                                <span class="help-block">
                                    @Html.ValidationMessageFor(model => model.LayoutName, "", new { @class = "text-danger" })
                                </span>
                            </div>
                        </div>
                        <span class="help-block">
                            @Html.ValidationMessageFor(model => model.meetingRoomLayoutId, "", new { @class = "text-danger" })
                        </span>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MeetingRoomStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.CheckBoxFor(model => model.MeetingRoomStatus, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MeetingRoomStatus, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                            <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "Room")';return false;">Cancel</button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div id="lookupLayout" class="modal fade" data-keyboard="false">
    <div class="page-loading page-loading-boxed">
        <img src="../../assets/global/img/loading-spinner-grey.gif" alt="" class="loading">
        <span>
            &nbsp;&nbsp;Loading...
        </span>
    </div>
    <div class="modal-dialog modal-lg">

        <div class="portlet box purple">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i>Layout List
                </div>
            </div>
            <div class="portlet-body">
                <div class="modal-content">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>

    </div>
</div>

<script>
    $(document).ready(function () {
        $.ajax({
            url: "/Layout/GetAllLayout",
            type: "GET",
            contentType: "application/json; charset=utf-8",
            datatype: JSON,
            success: function (data) {
                var $select = $('#LayoutName');
                $("#LayoutName").empty();
                $("#LayoutName").append("<option value='0'>--Select Layout--</option>");
                console.log(data);
                $(data).each(function (index) {
                    console.log(index);
                    $('<option>', {
                        value: data[index].Id
                    }).html(data[index].meetingRoomLayoutTitle).appendTo($select);
                });
            },
            error: function (data) { }
        });
    });

    //$(document).ready(function () {
    //    //Call EmpDetails jsonResult Method
    //    $.getJSON("/Equipment/GetEquipment",
    //        function (json) {
    //            console.log(json);
    //            //var tr;
    //            ////Append each row to html table
    //            //for (var i = 0; i < json.length; i++) {
    //            //    tr = $('<tr/>');
    //            //    tr.append("<td>" + json[i].Id + "</td>");
    //            //    tr.append("<td>" + json[i].Name + "</td>");
    //            //    tr.append("<td>" + json[i].City + "</td>");
    //            //    tr.append("<td>" + json[i].Address + "</td>");
    //            //    $('table').append(tr);
    //            //}
    //        });
    //});

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#displayImage').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#file").change(function () {
        readURL(this);
    });
</script>

MeetingRoom.VDI.Web/Views/Room/Details.cshtml
@model MeetingRoom.VDI.Web.Models.RoomViewModel

@{
    ViewBag.Title = "Details Room";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Create Room</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Details Room
            </div>
            <p></p>
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.MeetingRoomTitle)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MeetingRoomTitle)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.MeetingRoomDescription)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MeetingRoomDescription)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.MeetingRoomCapacity)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MeetingRoomCapacity)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.MeetingRoomPrice)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MeetingRoomPrice)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.MeetingRoomStatus)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MeetingRoomStatus)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.MeetingRoomImage)
                    </dt>

                    <dd>
                        <img alt="" src="@ViewBag.Base64String" style="height:100px;width:200px;" />
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>



<p>
    <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit", "Room", new { id = Model.Id })';return false;">Edit</button>
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "Room")';return false;">Cancel</button>
</p>

MeetingRoom.VDI.Web/Views/Room/Edit.cshtml
@model MeetingRoom.VDI.Web.Models.EditRoomViewModel

@{
    ViewBag.Title = "Edit Room";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edit Room</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Edit Room
            </div>
            <p></p>

            @using (Html.BeginForm("Edit", "Room", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.MeetingRoomTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MeetingRoomTitle, new { htmlAttributes = new { @class = "form-control", @style = "width:150px" } })
                        @Html.ValidationMessageFor(model => model.MeetingRoomTitle, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MeetingRoomDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MeetingRoomDescription, new { htmlAttributes = new { @class = "form-control", @style = "width:250px" } })
                        @Html.ValidationMessageFor(model => model.MeetingRoomDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MeetingRoomCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MeetingRoomCapacity, new { htmlAttributes = new { @class = "form-control", @style = "width:250px" } })
                        @Html.ValidationMessageFor(model => model.MeetingRoomCapacity, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MeetingRoomPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MeetingRoomPrice, new { htmlAttributes = new { @class = "form-control", @style = "width:250px" } })
                        @Html.ValidationMessageFor(model => model.MeetingRoomPrice, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MeetingRoomStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MeetingRoomStatus, new { htmlAttributes = new { @class = "form-control", @style = "width:250px" } })
                        @Html.ValidationMessageFor(model => model.MeetingRoomStatus, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MeetingRoomImage, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" id="file" name="file" multiple="multiple" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MeetingRoomImage, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <img id="displayImage" alt="" src="@ViewBag.Base64String" style="height:100px;width:200px;" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "Room")';return false;">Cancel</button>
                    </div>
                </div>
            </div>
            }

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $.ajax({
            url: "/Layout/GetLayout",
            type: "GET",
            contentType: "application/json; charset=utf-8",
            datatype: JSON,
            success: function (data) {
                var $select = $('#LayoutName');
                $("#LayoutName").empty();
                $("#LayoutName").append("<option value='0'>--Select Layout--</option>");

                $(data.Data).each(function (index) {
                    console.log(index);
                    $('<option>', {
                        value: data.Data[index].Id
                    }).html(data.Data[index].meetingRoomLayoutTitle).appendTo($select);
                });
            },
            error: function (data) { }
        });
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#displayImage').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#file").change(function () {
        readURL(this);
    });
</script>