MeetingRoom.VDI.Web/Controllers/OfflinePaymentController.cs
using AutoMapper;
using MeetingRoom.VDI.Core.Interfaces;
using MeetingRoom.VDI.Core.Models;
using MeetingRoom.VDI.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetingRoom.VDI.Web.Controllers
{
    public class OfflinePaymentController : Controller
    {
        private readonly IOfflinePayment _offlinePaymentService;

        public OfflinePaymentController(IOfflinePayment offlinePaymentService)
        {
            _offlinePaymentService = offlinePaymentService;
        }

        // GET: OfflinePayment
        public ActionResult Index()
        {
            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var output = _offlinePaymentService.GetAll();

            return View(output);
        }

        // GET: Layout/Create
        public ActionResult Create()
        {
            //if (!SecurityHelper.IsUserInTeam("SupervisorInventory"))
            //    return RedirectToAction("AccessDenied", "Account");

            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var model = new CreatePaymentViewModel();

            return View(model);
        }

        // POST: Layout/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreatePaymentViewModel model)
        {
            if (ModelState.IsValid)
            {
                byte[] rawBytes = null;
                if (Request.Files.Count > 0)
                {

                    var inputFile = Request.Files[0];
                    var fileNm = Request.Files[0].FileName;
                    HttpPostedFileBase hpf = Request.Files[0] as HttpPostedFileBase;
                    Stream fileStream = inputFile.InputStream;
                    rawBytes = new byte[fileStream.Length];
                    fileStream.Read(rawBytes, 0, Convert.ToInt32(fileStream.Length));
                }

                Mapper.CreateMap<CreatePaymentViewModel, Payment>();

                var newPayment = Mapper.Map<CreatePaymentViewModel, Payment>(model);
                newPayment.StrukImage = rawBytes;

                _offlinePaymentService.Create(newPayment);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: OfflinePayment/Edit/5
        public ActionResult Edit(int id)
        {
            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var payment = _offlinePaymentService.GetById(id);

            Mapper.CreateMap<Payment, EditPaymentViewModel>();
            var model = Mapper.Map<Payment, EditPaymentViewModel>(payment);

            if (model.StrukImage != null)
            {
                ViewBag.Base64String = "data:image/png;base64," + Convert.ToBase64String(model.StrukImage, 0, model.StrukImage.Length);
            }


            return View(model);
        }

        // POST: OfflinePayment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EditPaymentViewModel model)
        {
            if (ModelState.IsValid)
            {
                byte[] rawBytes = null;
                if (Request.Files.Count > 0)
                {
                    var inputFile = Request.Files[0];
                    var fileNm = Request.Files[0].FileName;
                    HttpPostedFileBase hpf = Request.Files[0] as HttpPostedFileBase;
                    Stream fileStream = inputFile.InputStream;
                    rawBytes = new byte[fileStream.Length];
                    fileStream.Read(rawBytes, 0, Convert.ToInt32(fileStream.Length));
                }

                Mapper.CreateMap<EditPaymentViewModel, Payment>();
                //.ForMember(s => s.Brand, o => o.Ignore());

                var editPayment = Mapper.Map<EditPaymentViewModel, Payment>(model);
                editPayment.StrukImage = rawBytes;
                //editBrand.UBy = User.Identity.Name;

                _offlinePaymentService.Update(editPayment);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult UpdatePayment(string reservedCode, HttpPostedFileBase fileUpload)
        {
            string message = "";
            if (ModelState.IsValid)
            {
                byte[] rawBytes = null;
                if (Request.Files.Count > 0)
                {
                    var inputFile = Request.Files[0];
                    var fileNm = Request.Files[0].FileName;
                    HttpPostedFileBase hpf = Request.Files[0] as HttpPostedFileBase;
                    Stream fileStream = inputFile.InputStream;
                    rawBytes = new byte[fileStream.Length];
                    fileStream.Read(rawBytes, 0, Convert.ToInt32(fileStream.Length));
                }

                var payment = _offlinePaymentService.GetByReservedCode(reservedCode);
                payment.StrukImage = rawBytes;

                message = _offlinePaymentService.Update(payment);
                //return RedirectToAction("Index");
            }
      
            return Json(message, JsonRequestBehavior.AllowGet);
            //return View();
        }
    }
}

MeetingRoom.VDI.Web/Views/OfflinePayment/Create.cshtml
@model MeetingRoom.VDI.Web.Models.CreatePaymentViewModel

@{
                /**/

                ViewBag.Title = "Process Payment";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Process Payment</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title pull-left">
                    Process Payment
                </div>
               
                <div class="clearfix"></div>
            </div>
            <p></p>

            @using (Html.BeginForm("Create", "OfflinePayment", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.BookingCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BookingCode, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.BookingCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BookingDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BookingDate, new { htmlAttributes = new { @class = "form-control", @style = "width:250px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.BookingDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ClientName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ClientName, new { htmlAttributes = new { @class = "form-control", @style = "width:250px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.RoomLayout, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.RoomLayout, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.RoomLayout, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TotalPayment, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TotalPayment, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.TotalPayment, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PaymentType, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PaymentType, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.PaymentType, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.AmountToBePaid, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AmountToBePaid, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.AmountToBePaid, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.StrukImage, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="file" id="inputFile" multiple="multiple" />
                            <p>
                                <img alt="" id="displayImage" src="@ViewBag.Base64String" style="height:100px;width:200px;" />
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                            <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "OfflinePayment")';return false;">Cancel</button>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#displayImage').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#inputFile").change(function () {
        readURL(this);
    });
</script>

MeetingRoom.VDI.Web/Views/OfflinePayment/Edit.cshtml
@model MeetingRoom.VDI.Web.Models.EditPaymentViewModel

@{
    ViewBag.Title = "Process Payment";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Process Payment</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title pull-left">
                    Process Payment
                </div>

                @if (Model.Paid == true)
                {
                    <div class="panel-title pull-right">
                        <p style="color: lime;font-family: Impact;">Paid!</p>
                    </div>
                }
                <div class="clearfix"></div>
            </div>
            <p></p>

            @using (Html.BeginForm("Edit", "OfflinePayment", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.BookingCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BookingCode, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.BookingCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BookingDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BookingDate, new { htmlAttributes = new { @class = "form-control", @style = "width:250px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.BookingDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ClientName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ClientName, new { htmlAttributes = new { @class = "form-control", @style = "width:250px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.RoomLayout, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.RoomLayout, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.RoomLayout, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TotalPayment, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TotalPayment, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.TotalPayment, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PaymentType, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PaymentType, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.PaymentType, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.AmountToBePaid, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AmountToBePaid, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.AmountToBePaid, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @style = "width:150px", @readonly = "" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.StrukImage, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="file" id="inputFile" multiple="multiple" />
                            <p>
                                <img alt="" id="displayImage" src="@ViewBag.Base64String" style="height:100px;width:200px;" />
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                            <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "OfflinePayment")';return false;">Cancel</button>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#displayImage').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#inputFile").change(function () {
        readURL(this);
    });
</script>

MeetingRoom.VDI.Web/Views/OfflinePayment/Index.cshtml
@model IEnumerable<MeetingRoom.VDI.Core.Models.Payment>

@{
    ViewBag.Title = "Offline Payment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Offline Payment</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Offline Payment
            </div>

            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Reservation Code</th>
                                <th>Reservation Date</th>
                                <th>Client Name</th>
                                <th>Total Payment</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var payment in Model)
                            {
                                <tr class="odd gradeX">
                                    <td>
                                        @Html.DisplayFor(modelItem => payment.ReservedCode)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => payment.BookingDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => payment.ClientName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => payment.TotalPayment)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Process", "Edit", new { id = payment.Id }, new { @class = "btn btn-primary btn-large" })
                                        @*@Html.ActionLink("Process", "Edit", new { id = payment.Id })*@
                                        @*@Html.ActionLink("Details", "Details", new { id = payment.Id })*@
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>