MeetingRoom.VDI.Web/Models/BeverageViewModel.cs
using Mvc.JQuery.Datatables;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MeetingRoom.VDI.Web.Models
{
    public class BeverageViewModel
    {
        public int Id { get; set; }
        [DisplayName("Description")]
        [DataTables(Width = "200px")]
        public string meetingRoomFoodDrinkDescription { get; set; }
        [DisplayName("Price")]
        [DataTables(Width = "50px")]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public decimal meetingRoomFoodDrinkPrice { get; set; }
        [DisplayName("Title")]
        [DataTables(Width = "50px")]
        public string meetingRoomFoodDrinkTitle { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
    }

    public class CreateBeverageViewModel
    {
        public int Id { get; set; }
        [DisplayName("Description")]
        [DataTables(Width = "200px")]
        public string meetingRoomFoodDrinkDescription { get; set; }
        [DisplayName("Price")]
        [DataTables(Width = "50px")]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public decimal meetingRoomFoodDrinkPrice { get; set; }
        [DisplayName("Title")]
        [DataTables(Width = "50px")]
        public string meetingRoomFoodDrinkTitle { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
    }

    public class EditBeverageViewModel
    {
        public int Id { get; set; }
        [DisplayName("Description")]
        [DataTables(Width = "200px")]
        public string meetingRoomFoodDrinkDescription { get; set; }
        [DisplayName("Price")]
        [DataTables(Width = "50px")]
        //[DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public decimal meetingRoomFoodDrinkPrice { get; set; }
        [DisplayName("Title")]
        [DataTables(Width = "50px")]
        public string meetingRoomFoodDrinkTitle { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
    }
}

MeetingRoom.VDI.Web/Controllers/BeverageController.cs
using AutoMapper;
using MeetingRoom.VDI.Core.Const;
using MeetingRoom.VDI.Core.Interfaces;
using MeetingRoom.VDI.Core.Models;
using MeetingRoom.VDI.Web.Models;
using Mvc.JQuery.Datatables;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetingRoom.VDI.Web.Controllers
{
    public class BeverageController : Controller
    {
        private readonly IBeverage _beverageService;

        public BeverageController(IBeverage beverageService)
        {
            _beverageService = beverageService;
        }

        public ActionResult BeverageList()
        {
            return PartialView();
        }

        // GET: Beverage
        public ActionResult Index()
        {
            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var output = _beverageService.GetAll();

            return View(output);
        }

        // GET: Beverage/Details/5
        public ActionResult Details(int id)
        {
            //if (!SecurityHelper.IsUserInTeam("SupervisorInventory"))
            //    return RedirectToAction("AccessDenied", "Account");

            var Beverage = _beverageService.GetById(id);

            Mapper.CreateMap<Beverage, BeverageViewModel>();
            var model = Mapper.Map<Beverage, BeverageViewModel>(Beverage);

            return View(model);
        }

        // GET: Beverage/Create
        public ActionResult Create()
        {
            //if (!SecurityHelper.IsUserInTeam("SupervisorInventory"))
            //    return RedirectToAction("AccessDenied", "Account");

            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var model = new CreateBeverageViewModel();

            return View(model);
        }

        // POST: Beverage/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateBeverageViewModel model)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<CreateBeverageViewModel, Beverage>();
                //.ForMember(s => s.Brand, o => o.Ignore());

                var newBeverage = Mapper.Map<CreateBeverageViewModel, Beverage>(model);

                //newSubBrand.IBy = User.Identity.Name;
                _beverageService.Create(newBeverage);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Beverage/Edit/5
        public ActionResult Edit(int id)
        {
            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var Beverage = _beverageService.GetById(id);

            Mapper.CreateMap<Beverage, EditBeverageViewModel>();
            var model = Mapper.Map<Beverage, EditBeverageViewModel>(Beverage);

            return View(model);
        }

        // POST: Beverage/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EditBeverageViewModel model)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<EditBeverageViewModel, Beverage>();
                //.ForMember(s => s.Brand, o => o.Ignore());

                var editBeverage = Mapper.Map<EditBeverageViewModel, Beverage>(model);
                //editBrand.UBy = User.Identity.Name;

                _beverageService.Update(editBeverage);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Beverage/Delete/5
        public ActionResult Delete(int id)
        {
            var strProfile = this.Session["UserProfile"];
            var strPass = this.Session["UserPass"];
            var IsLogin = this.Session["IsLogin"];
            var IsAdmin = this.Session["IsAdmin"];

            if (Convert.ToInt16(IsLogin) == 0 && Convert.ToInt16(IsAdmin) == 0)
                return RedirectToAction("AccessDenied", "Account");

            var Beverage = _beverageService.GetById(id);

            Mapper.CreateMap<Beverage, EditBeverageViewModel>();
            var model = Mapper.Map<Beverage, EditBeverageViewModel>(Beverage);

            return View(model);
        }

        // POST: Beverage/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, EditBeverageViewModel model)
        {
            try
            {
                Mapper.CreateMap<EditBeverageViewModel, Beverage>();
                var deleteBeverage = Mapper.Map<EditBeverageViewModel, Beverage>(model);

                _beverageService.Delete(deleteBeverage.Id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public DataTablesResult<BeverageViewModel> GetIndex(DataTablesParam dataTableParam, string filterData = "")
        {
            return GetAll<BeverageViewModel>(dataTableParam, filterData);
        }

        public DataTablesResult<T> GetAll<T>(DataTablesParam dataTableParam, string filterData = "")
        {
            if (dataTableParam.iDisplayLength == 0)
                dataTableParam.iDisplayLength = GlobalSetting.DEFAULT_PAGESIZE;

            var pageIndex = Convert.ToInt32(Math.Ceiling((double)dataTableParam.iDisplayStart / dataTableParam.iDisplayLength) + 1);

            List<Beverage> filter = null;
            if (!String.IsNullOrEmpty(filterData))
                filter = JsonConvert.DeserializeObject<List<Beverage>>(filterData);

            Beverage search = null;
            if (!String.IsNullOrEmpty(dataTableParam.sSearch))
            {
                search = new Beverage();
                search.meetingRoomFoodDrinkTitle = dataTableParam.sSearch;
            }

            var pagedData = _beverageService.GetAll(filter, search, pageIndex, dataTableParam.iDisplayLength);

            Mapper.CreateMap<Beverage, T>();
            var data = Mapper.Map<IEnumerable<Beverage>, IEnumerable<T>>(pagedData.Data);

            dataTableParam.iDisplayStart = 0;
            dataTableParam.sSearch = "";
            var result = DataTablesResult.Create(data.AsQueryable(), dataTableParam);

            result.Data.iTotalRecords = pagedData.TotalRecord;
            result.Data.iTotalDisplayRecords = pagedData.TotalRecord;

            return result;
        }

        public JsonResult GetBeverage()
        {
            var foodList = _beverageService.GetBeverage();
            return Json(foodList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllBeverage()
        {
            var foodList = _beverageService.GetAll();
            return Json(foodList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPriceFood(int Id, int Qty)
        {
            var foodList = _beverageService.GetPriceFood(Id, Qty);
            return Json(foodList, JsonRequestBehavior.AllowGet);
        }
    }
}

MeetingRoom.VDI.Web/Views/Beverage/BeverageList.cshtml
@using MeetingRoom.VDI.Core.Const
@*@using App.Core.Enums*@
@using MeetingRoom.VDI.Core.Models
@using MeetingRoom.VDI.Web.Controllers
@using MeetingRoom.VDI.Web.Helper
@using Mvc.JQuery.Datatables
@using Mvc.JQuery.Datatables.Serialization

@{
    var vm = Html.DataTableVm("GridBeverage", (BeverageController h) => h.GetIndex(null, null));

    vm.JsOptions.Add("scrollY", "360");
    vm.JsOptions.Add("scrollX", "1480");
    //vm.JsOptions.Add("iDisplayLength", 25);
    vm.JsOptions.Add("fnCreatedRow", new Raw(@"function( nRow, aData, iDataIndex ) {$(nRow).attr('data-id', aData[0]);}"));
    vm.TableClass = "table table-striped table-bordered table-hover";
    //vm.FilterOn("Address").None();

    vm.ShowSearch = true;
    vm.ColumnFilter = false;
    vm.TableTools = true;
    vm.StateSave = false;
    vm.AutoWidth = false;
    vm.LengthMenu = CustomDTHelper.LengthMenuVm();
    vm.PageLength = GlobalSetting.DEFAULT_PAGESIZE; //... and set a default
    vm.ColVis = false;

    if (ViewBag.Filter != null)
    {
        ViewBag.FilterData = Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.Filter);
    }
}


<script type="text/javascript">
    function LinkDetail(data, type, full) {
        return '<a href="/Beverage/Details/' + full[0] + '">' + data + '</em>';
    }

    $('#GridBeverage tbody').on('dblclick', 'tr', function () {
        var id = $(this).attr('data-id');
        var url = "/Beverage/Details/" + id;
        window.location.href = url;
    });
</script>

@Html.Partial("MyDataTable", vm)

MeetingRoom.VDI.Web/Views/Beverage/Create.cshtml
@model MeetingRoom.VDI.Web.Models.CreateBeverageViewModel

@{
    ViewBag.Title = "Create Beverage";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Create Beverage</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Create Beverage
            </div>
            <p></p>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomFoodDrinkTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.EditorFor(model => model.meetingRoomFoodDrinkTitle, new { htmlAttributes = new { @class = "form-control", @placeholder = "FoodDrink Name", @style = "width:150px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomFoodDrinkTitle, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomFoodDrinkDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.TextAreaFor(model => model.meetingRoomFoodDrinkDescription, new { htmlAttributes = new { style = "width:250px", rows = "3", @class = "form-control", @placeholder = "FoodDrink Description" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomFoodDrinkDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomFoodDrinkPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            <span class="input-group-addon">Rp</span>
                            @Html.EditorFor(model => model.meetingRoomFoodDrinkPrice, new { htmlAttributes = new { @class = "form-control", @placeholder = "FoodDrink Price", @style = "width:150px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomFoodDrinkPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "Beverage")';return false;">Cancel</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

MeetingRoom.VDI.Web/Views/Beverage/Delete.cshtml
@model MeetingRoom.VDI.Web.Models.EditBeverageViewModel

@{
    ViewBag.Title = "Delete Beverage";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Delete Beverage</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Delete Beverage
            </div>
            <p></p>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomFoodDrinkTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.EditorFor(model => model.meetingRoomFoodDrinkTitle, new { htmlAttributes = new { @class = "form-control", @style = "width:150px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomFoodDrinkTitle, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomFoodDrinkDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.EditorFor(model => model.meetingRoomFoodDrinkDescription, new { htmlAttributes = new { @class = "form-control", @style = "width:250px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomFoodDrinkDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomFoodDrinkPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            <span class="input-group-addon">Rp</span>
                            @Html.EditorFor(model => model.meetingRoomFoodDrinkPrice, new { htmlAttributes = new { @class = "form-control", @style = "width:150px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomFoodDrinkPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Delete" class="btn btn-primary" />
                            <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "Beverage")';return false;">Cancel</button>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

MeetingRoom.VDI.Web/Views/Beverage/Details.cshtml
@model MeetingRoom.VDI.Web.Models.BeverageViewModel

@{
    ViewBag.Title = "Details Equipment";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Detail Beverage</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Details Beverage
            </div>
            <p></p>
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.meetingRoomFoodDrinkTitle)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.meetingRoomFoodDrinkTitle)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.meetingRoomFoodDrinkDescription)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.meetingRoomFoodDrinkDescription)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.meetingRoomFoodDrinkPrice)
                    </dt>

                    <dd>
                        Rp. @Html.DisplayFor(model => model.meetingRoomFoodDrinkPrice)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>



<p>
    <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit", "Beverage", new { id = Model.Id })';return false;">Edit</button>
    <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "Beverage")';return false;">Cancel</button>
</p>

MeetingRoom.VDI.Web/Views/Beverage/Edit.cshtml
@model MeetingRoom.VDI.Web.Models.EditBeverageViewModel

@{
    ViewBag.Title = "Edit Beverage";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edit Beverage</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Edit Beverage
            </div>
            <p></p>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomFoodDrinkTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.EditorFor(model => model.meetingRoomFoodDrinkTitle, new { htmlAttributes = new { @class = "form-control", @style = "width:150px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomFoodDrinkTitle, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomFoodDrinkDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            @Html.EditorFor(model => model.meetingRoomFoodDrinkDescription, new { htmlAttributes = new { @class = "form-control", @style = "width:250px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomFoodDrinkDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meetingRoomFoodDrinkPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="form-group input-group">
                            <span class="input-group-addon">Rp</span>
                            @Html.EditorFor(model => model.meetingRoomFoodDrinkPrice, new { htmlAttributes = new { @class = "form-control", @style = "width:150px" } })
                            @Html.ValidationMessageFor(model => model.meetingRoomFoodDrinkPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                            <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "Beverage")';return false;">Cancel</button>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

MeetingRoom.VDI.Web/Views/Beverage/Index.cshtml
@model IEnumerable<MeetingRoom.VDI.Core.Models.Beverage>

@{
    ViewBag.Title = "Master Beverage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Beverage</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Beverage
            </div>

            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Prices</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var mstMeetingroom in Model)
                            {
                                <tr class="odd gradeX">
                                    <td>
                                        @Html.DisplayFor(modelItem => mstMeetingroom.meetingRoomFoodDrinkTitle)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => mstMeetingroom.meetingRoomFoodDrinkDescription)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => mstMeetingroom.meetingRoomFoodDrinkPrice)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = mstMeetingroom.Id }, new { @class = "btn btn-primary btn-large" }) |
                                        @Html.ActionLink("Details", "Details", new { id = mstMeetingroom.Id }, new { @class = "btn btn-primary btn-large" })|
                                        @Html.ActionLink("Delete", "Delete", new { id = mstMeetingroom.Id }, new { @class = "btn btn-primary btn-large" })
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
                <p>
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("Create", "Beverage")';">Create</button>
                </p>
            </div>
        </div>
    </div>
</div>